# Generated by Django 2.1.7 on 2019-04-14 15:01

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bigimg',
            field=models.ImageField(blank=True, upload_to=users.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkImg',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='smallPic',
            field=models.ImageField(blank=True, upload_to=users.models.user_directory_path),
        ),
    ]
