# Generated by Django 2.1.7 on 2019-04-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190414_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bigimg',
        ),
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, default='Anonym', max_length=128),
        ),
    ]
