# Generated by Django 2.1.7 on 2019-04-01 10:02

import app_product.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APP',
            fields=[
                ('appID', models.AutoField(primary_key=True, serialize=False)),
                ('appname', models.CharField(max_length=128)),
                ('body', models.TextField(max_length=500)),
                ('downloads', models.IntegerField(default=0)),
                ('keywords', django.contrib.postgres.fields.jsonb.JSONField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastMod', models.DateField(auto_now=True)),
                ('website', models.URLField(blank=True, max_length=512, null=True)),
                ('contectEmail', models.EmailField(max_length=70)),
                ('sourcefiles', models.FileField(upload_to=app_product.models.user_directory_path)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='appKomments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('kommentar', models.CharField(max_length=1024)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.APP')),
            ],
        ),
    ]
