# Generated by Django 2.1.7 on 2019-04-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0006_auto_20190401_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='typOfAccount',
            field=models.CharField(choices=[('ST', 'Student'), ('SA', 'Staff'), ('PR', 'Professor'), ('Fr', 'Externer Student'), ('All', 'Non Type')], default='All', max_length=4),
        ),
    ]
