# Generated by Django 2.1.7 on 2019-04-01 18:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0007_auto_20190401_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=20),
        ),
    ]
