# Generated by Django 2.1.7 on 2019-04-03 15:20

import app_product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0008_auto_20190403_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='sourcefiles',
            field=models.FileField(blank=True, upload_to=app_product.models.user_directory_path),
        ),
    ]
