# Generated by Django 2.1.7 on 2019-04-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0009_auto_20190401_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='keywords',
        ),
    ]
