# Generated by Django 2.1.7 on 2019-04-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0009_auto_20190403_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='linkImg',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
