# Generated by Django 2.1.7 on 2019-04-01 18:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0010_remove_app_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='keywords',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
