# Generated by Django 2.1.7 on 2019-04-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0011_app_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='keywords',
        ),
    ]
