# Generated by Django 2.1.7 on 2019-04-01 19:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0012_remove_app_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='keywords',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
    ]
