# Generated by Django 2.1.7 on 2019-04-01 19:08

import app_product.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0015_auto_20190401_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='keywords',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=app_product.models.get_default_data, null=True),
        ),
    ]
