# Generated by Django 2.1.7 on 2019-04-01 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0016_auto_20190401_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='keywords',
        ),
    ]
